title: LEOM HUB
author: Aransiola Ayodele
email: leomdevs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Web development

# social links
twitter_username: @leomdevs
github_username:  @CodeLeom

show_excerpts: true # set to false to remove excerpts on the homepage

theme: matama
