title: Leom Hub
author: Aransiola Ayodele
email: leomdevs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this blog is developed to train and inspire upcoming developers.
  We live to code and we code to live...

# social links
twitter_username: @leomdevs
github_username:  @CodeLeom

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
